version: "3.9"

services:
  web:
    container_name: web
    image: evercharge/web
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/opt/web
    ports:
      - "${DOCKER_LOCAL_WEB_PORT:-9000}:9000"
    networks:
      - web
    environment:
      - FLASK_DEBUG=True
      - EVERCHARGE_ENV

networks:
  web:
