version: "3.9"

services:
  web:
    container_name: web
    image: evercharge/web
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - web
    environment:
      - FLASK_DEBUG=True
      - NS_ACCOUNT
      - NS_CONSUMER_KEY
      - NS_CONSUMER_SECRET
      - NS_TOKEN_KEY
      - NS_TOKEN_SECRET

networks:
  web:
