version: "3.9"

services:
  web:
    container_name: web
    image: evercharge/web
    build:
      context: ./
      dockerfile: Dockerfile
      no_cache: true
      
    ports:
      - "80:80"
    networks:
      - web
    environment:
      - FLASK_DEBUG=True
      - EVERCHARGE_ENV
    

networks:
  web:
