branch-defaults:
  feature-new-design:
    environment: WebMain-38-env
  master:
    environment: webMain-env
  redesign:
    environment: webMain-env-stage
  web-103-transfer-blog-to-suburl:
    environment: webMain-env-new-blog
  web-49-enable-compression:
    environment: webMain-env-stage
global:
  application_name: web-main
  default_ec2_keyname: EverChargeMaster
  default_platform: Python 3.8 running on 64bit Amazon Linux 2/3.2.0
  default_region: us-west-2
  profile: eb-cli
  sc: git
