branch-defaults:
  feature-new-design:
    environment: webMain-staging-env
  master:
    environment: webMain-env
  redesign:
    environment: webMain-env-stage
  web-103-transfer-blog-to-suburl:
    environment: webMain-env-new-blog
  web-49-enable-compression:
    environment: webMain-env-stage
global:
  application_name: web-main
  default_ec2_keyname: EverChargeMaster
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Docker running on
    64bit Amazon Linux/2.12.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
