branch-defaults:
  master:
    environment: webMain-env
  web-103-transfer-blog-to-suburl:
    environment: webMain-env-new-blog
  web-49-enable-compression:
    environment: webMain-env-stage
global:
  application_name: web-main
  default_ec2_keyname: EverChargeMaster
  default_platform: 64bit Amazon Linux 2015.03 v2.0.0 running Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: git
