branch-defaults:
  master:
    environment: webMain-env
global:
  application_name: web-main
  default_ec2_keyname: EverChargeMaster
  default_platform: 64bit Amazon Linux 2015.03 v2.0.0 running Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: git

container_commands:
    01_setup_apache:
        command: "cp .ebextensions/enable_mod_deflate.conf /etc/httpd/conf.d/enable_mod_deflate.conf"