branch-defaults:
  feature-new-design:
    environment: WebMain-38-env
  master:
    environment: WebMain-38-env
  master-scaleable:
    environment: Webmain-staging38-env
  redesign:
    environment: webMain-env-stage
  web-103-transfer-blog-to-suburl:
    environment: webMain-env-new-blog
  web-49-enable-compression:
    environment: webMain-env-stage
environment-defaults:
  WebMain-38-env:
    branch: null
    repository: null
global:
  application_name: web-main
  default_ec2_keyname: EverChargeMaster
  default_platform: Python 3.8 running on 64bit Amazon Linux 2/3.2.0
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
