FROM ubuntu:18.04

MAINTAINER Nikolay Golub <nikolay.v.golub@gmail.com>

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=US/Eastern

RUN apt-get update && \
    apt-get install -y git python3-dev python3-pip
