permissions:
  id-token: write
  contents: read
name: Pulumi
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: configure aws creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::032719859041:role/github-marketing-blog
          role-duration-seconds: 900
          aws-region: us-west-2 
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Pulumi Create Stack
        uses: pulumi/actions@v3
        continue-on-error: true
        with:
          command: stack init --non-interactive
          stack-name: evercharge/marketing-${{ github.ref_name }}
      - name: Pulumi Preview
        uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: evercharge/marketing-${{ github.ref_name }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}